### ISSUE TITLE
Animation duplication detection in the presence of camera movement

### ISSUE THREAD

**Issue by endways2** [ShuhongChen/eisai-anime-interpolator#14]
Hello! I’ve read your paper. Your work is excellent, but I wonder how you processed clips with camera movement while preparing your dataset. When camera movement is present, it is often in 24 FPS, while animations are still in 12 FPS. You cannot remove duplicate frames because frames are not entirely identical. Only some parts of them are. An example would be AnimeInterp’s demo which you have mentioned in your paper. The camera moves every frame, but the characters’ poses progress only every other frame, resulting in stop-and-go artifacts that the regression model cannot simply remove.

**Comment by ShuhongChen** [comment]
> When camera movement is present, it is often in 24 FPS, while animations are still in 12 FPS. You cannot remove duplicate frames because frames are not entirely identical

Thanks for your interest in our work; yes you're right, this causes data collection problems not just for this project but for our other projects also.  I assume it's common practice in compositing/satsuei, and it happens a lot

When prepping the dataset (RRLD), we try to [remove pan-like triplets](https://github.com/ShuhongChen/eisai-anime-interpolator/blob/29f50de172188a871bff4d01453cd2252d4c64b9/_scripts/rrld_filter.py#L118) by discarding frames with too much movement, or with low variance in movement direction

This shouldn't be a problem for artists using the system at inference though, since there's direct access to colored frames/shiage, before compositing with background/haikei
