### ISSUE TITLE
ssl.pt and dtm.pt checkpoints in train.py

### ISSUE THREAD

**Issue by judithcaldes** [ShuhongChen/eisai-anime-interpolator#24]
Hi there,

I'm wondering how you generate the ssl.pt and dtm.pt checkpoints during the training process. In your train.py script, you generate several checkpoints, but I can't find in your code where the ssl.pt and dtm.pt checkpoints are generated. I need them for the interpolat.py script. Could you provide some guidance on this?

**Comment by ShuhongChen** [comment]
Hello, I looked around for the exact script that did this, but unfortunately I can't find it anywhere; sorry about that, it's been a while since I ran the code for this project

From what I remember, the `ssl.pt` and `dtm.pt` checkpoints should just be `torch.save` of the `state_dict` of the pytorch lightning checkpoint that gets saved during training; I remember I did this so that the repo release would be easier to run

**Comment by judithcaldes** [comment]
You're right, using torch.save solves the issue. Thank you!
