### ISSUE TITLE
A Little Error

### ISSUE THREAD

**Issue by 98mxr** [ShuhongChen/eisai-anime-interpolator#3]
eisai-anime-interpolator-master/_train/frame_interpolation/models/ssldtm.py, line 119
`kornia.morphology.open` should be `kornia.morphology.opening` in Kornia ver. 0.6.6

**Comment by ShuhongChen** [comment]
Hi, thanks for pointing this out; I think we'll stick with kornia 0.5.2 in the [dockerfile](https://github.com/ShuhongChen/eisai-anime-interpolator/blob/350d2418a0dd42784c19cf10dfdc420406718f00/_env/Dockerfile#L40) for now since it's the version used in original experiments

It worked when tested on my docker machine but if it throws an error for you let me know
